// Copyright (c) 2023 - Restate Software, Inc., Restate GmbH
//
// This file is part of the Restate Java SDK,
// which is released under the MIT license.
//
// You can find a copy of the license in file LICENSE in the root
// directory of this repository or package, or at
// https://github.com/restatedev/sdk-java/blob/main/LICENSE
package dev.restate.sdk.common;

import dev.restate.sdk.common.function.ThrowingFunction;
import java.nio.ByteBuffer;
import java.util.Objects;
import org.jspecify.annotations.Nullable;

/**
 * Interface defining serialization and deserialization of concrete types.
 *
 * <p>Serde implementations are provided in {@code JsonSerdes} in {@code sdk-api}, {@code KtSerdes}
 * in {@code sdk-api-kotlin}, {@code JacksonSerdes} in {@code sdk-serde-jackson}, {@code
 * ProtobufSerdes} in {@code sdk-serde-protobuf}.
 *
 * <p>You can create a custom one using {@link #using(String, ThrowingFunction, ThrowingFunction)}.
 */
public interface Serde<T> {

  byte[] serialize(@Nullable T value);

  default ByteBuffer serializeToByteBuffer(@Nullable T value) {
    // This is safe because we don't mutate the generated byte[] afterward.
    return ByteBuffer.wrap(serialize(value));
  }

  T deserialize(byte[] value);

  default T deserialize(ByteBuffer byteBuffer) {
    if (byteBuffer.hasArray()) {
      return deserialize(byteBuffer.array());
    }
    byte[] bytes = new byte[byteBuffer.remaining()];
    byteBuffer.get(bytes);
    return deserialize(bytes);
  }

  // --- Metadata about the serialized/deserialized content

  /**
   * Content-type to use in request/responses.
   *
   * <p>If null, the SDK assumes the produced output is empty. This might change in the future.
   */
  default @Nullable String contentType() {
    return "application/octet-stream";
  }

  /**
   * Like {@link #using(String, ThrowingFunction, ThrowingFunction)}, using content-type {@code
   * application/octet-stream}.
   */
  static <T> Serde<T> using(
      ThrowingFunction<T, byte[]> serializer, ThrowingFunction<byte[], T> deserializer) {
    return new Serde<>() {
      @Override
      public byte[] serialize(T value) {
        return serializer.asFunction().apply(Objects.requireNonNull(value));
      }

      @Override
      public T deserialize(byte[] value) {
        return deserializer.asFunction().apply(value);
      }
    };
  }

  /**
   * Create a {@link Serde} from {@code serializer}/{@code deserializer} lambdas, tagging with
   * {@code contentType}. Before invoking the serializer, we check that {@code value} is non-null.
   */
  static <T> Serde<T> using(
      String contentType,
      ThrowingFunction<T, byte[]> serializer,
      ThrowingFunction<byte[], T> deserializer) {
    return new Serde<>() {
      @Override
      public byte[] serialize(T value) {
        return serializer.asFunction().apply(Objects.requireNonNull(value));
      }

      @Override
      public T deserialize(byte[] value) {
        return deserializer.asFunction().apply(value);
      }

      @Override
      public @Nullable String contentType() {
        return contentType;
      }
    };
  }

  static <T> Serde<T> withContentType(String contentType, Serde<T> inner) {
    return new Serde<>() {
      @Override
      public byte[] serialize(@Nullable T value) {
        return inner.serialize(value);
      }

      @Override
      public ByteBuffer serializeToByteBuffer(@Nullable T value) {
        return inner.serializeToByteBuffer(value);
      }

      @Override
      public T deserialize(ByteBuffer byteBuffer) {
        return inner.deserialize(byteBuffer);
      }

      @Override
      public T deserialize(byte[] value) {
        return inner.deserialize(value);
      }

      @Override
      public @Nullable String contentType() {
        return contentType;
      }
    };
  }

  /** Noop {@link Serde} for void. */
  Serde<Void> VOID =
      new Serde<>() {
        @Override
        public byte[] serialize(Void value) {
          return new byte[0];
        }

        @Override
        public ByteBuffer serializeToByteBuffer(@Nullable Void value) {
          return ByteBuffer.allocate(0);
        }

        @Override
        public Void deserialize(byte[] value) {
          return null;
        }

        @Override
        public Void deserialize(ByteBuffer byteBuffer) {
          return null;
        }

        @Override
        public @Nullable String contentType() {
          return null;
        }
      };

  /** Pass through {@link Serde} for byte array. */
  Serde<byte[]> RAW =
      new Serde<>() {
        @Override
        public byte[] serialize(byte[] value) {
          return Objects.requireNonNull(value);
        }

        @Override
        public byte[] deserialize(byte[] value) {
          return value;
        }
      };

  /** Pass through {@link Serde} for {@link ByteBuffer}. */
  Serde<ByteBuffer> BYTE_BUFFER =
      new Serde<>() {

        @Override
        public byte[] serialize(@Nullable ByteBuffer byteBuffer) {
          if (byteBuffer == null) {
            return new byte[] {};
          }
          if (byteBuffer.hasArray()) {
            return byteBuffer.array();
          }
          byte[] bytes = new byte[byteBuffer.remaining()];
          byteBuffer.get(bytes);
          return bytes;
        }

        @Override
        public ByteBuffer serializeToByteBuffer(@Nullable ByteBuffer value) {
          return value;
        }

        @Override
        public ByteBuffer deserialize(byte[] value) {
          return ByteBuffer.wrap(value);
        }

        @Override
        public ByteBuffer deserialize(ByteBuffer byteBuffer) {
          return byteBuffer;
        }
      };
}
