/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.4.2/userguide/multi_project_builds.html
 */

rootProject.name = "sdk-java"

plugins { id("org.gradle.toolchains.foojay-resolver-convention") version "0.7.0" }

include(
    "admin-client",
    "sdk-common",
    "sdk-api",
    "sdk-api-kotlin",
    "sdk-core",
    "sdk-serde-jackson",
    "sdk-serde-protobuf",
    "sdk-request-identity",
    "sdk-http-vertx",
    "sdk-lambda",
    "sdk-testing",
    "sdk-api-gen-common",
    "sdk-api-gen",
    "sdk-api-kotlin-gen",
    "sdk-spring-boot",
    "sdk-spring-boot-starter",
    "sdk-spring-boot-kotlin-starter",
    "examples",
    "sdk-aggregated-javadocs",
    "test-services")

dependencyResolutionManagement { repositories { mavenCentral() } }
