import org.gradle.kotlin.dsl.withType
import org.jetbrains.dokka.gradle.AbstractDokkaTask
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
  `java-library`
  `java-conventions`
  `kotlin-conventions`
  `library-publishing-conventions`
  alias(libs.plugins.jsonschema2pojo)
  alias(libs.plugins.ksp)
  // Chicory AOT: compile .wasm to JVM bytecode at build time
  id("at.released.wasm2class.plugin") version "0.5.0"

  // https://github.com/gradle/gradle/issues/20084#issuecomment-1060822638
  id(libs.plugins.spotless.get().pluginId) apply false
}

description = "Restate SDK Core"

// ---------------------------------------------------------------------------
// Rust WASM build pipeline (merged from sdk-shared-core)
// ---------------------------------------------------------------------------

val rustSrcDir = file("src/main/rust")
val wasmReleaseDir = file("$rustSrcDir/target/wasm32-unknown-unknown/release")
val wasmFile = file("$wasmReleaseDir/restate_sdk_shared_core_wasm.wasm")
val wasmResourceDir = layout.buildDirectory.dir("wasm-resource")
val wasmResourceFile = wasmResourceDir.map { it.file("restate_sdk_shared_core_wasm.wasm") }

val compileRustToWasm by
    tasks.registering(Exec::class) {
      group = "build"
      description = "Compile the Rust WASM wrapper crate"
      workingDir = rustSrcDir
      commandLine("cargo", "build", "--target", "wasm32-unknown-unknown", "--release")
      inputs.dir("$rustSrcDir/src")
      inputs.file("$rustSrcDir/Cargo.toml")
      outputs.file(wasmFile)
    }

val cargoFmt by
    tasks.registering(Exec::class) {
      group = "formatting"
      description = "Format the Rust WASM wrapper crate with cargo fmt"
      workingDir = rustSrcDir
      commandLine("cargo", "fmt")
    }

tasks.matching { it.name == "spotlessApply" }.configureEach { dependsOn(cargoFmt) }

val copyWasm by
    tasks.registering(Copy::class) {
      group = "build"
      dependsOn(compileRustToWasm)
      from(wasmFile)
      into(wasmResourceDir)
    }

// Chicory AOT: compile .wasm → JVM bytecode
wasm2class {
  modules {
    targetPackage = "dev.restate.sdk.core.sharedcore.generated"
    create("SharedCoreWasm") { wasm = wasmResourceFile }
  }
}

tasks.named("precompileWasm2Class") { dependsOn(copyWasm) }

tasks.named("processResources") { dependsOn(copyWasm) }

tasks.withType<KotlinCompile>().configureEach {
  mustRunAfter(generateWasmMarker, "precompileWasm2Class")
}

// Generate the @WasmModuleInterface marker class with the absolute wasm file URI so the
// Chicory annotation processor can find it at compile time (it uses StandardLocation.CLASS_OUTPUT
// which is not reliable cross-tool, so a file: URI works around that).
val generatedWasmMarkerDir = layout.buildDirectory.dir("generated-wasm-marker")

val generateWasmMarker by
    tasks.registering {
      group = "build"
      dependsOn(copyWasm)
      inputs.file(wasmResourceFile)
      outputs.dir(generatedWasmMarkerDir)
      doLast {
        val wasmUri = wasmResourceFile.get().asFile.toURI().toString()
        val content =
            """
// AUTO-GENERATED — do not edit. Regenerated by generateWasmMarker Gradle task.
// Copyright (c) 2023 - Restate Software, Inc., Restate GmbH
//
// This file is part of the Restate Java SDK,
// which is released under the MIT license.
package dev.restate.sdk.core.sharedcore;

import com.dylibso.chicory.annotations.WasmModuleInterface;

/**
 * Marker class processed by Chicory's annotation processor. Generates
 * {@code SharedCoreWasm_ModuleExports} (typed wrapper for all WASM exports).
 */
@WasmModuleInterface("$wasmUri")
public final class SharedCoreWasm {}
    """
                .trimIndent() + "\n"
        val out =
            generatedWasmMarkerDir
                .get()
                .file("dev/restate/sdk/core/sharedcore/SharedCoreWasm.java")
                .asFile
        out.parentFile.mkdirs()
        out.writeText(content)
      }
    }

// ---------------------------------------------------------------------------
// Dependency configurations
// ---------------------------------------------------------------------------

val shade by configurations.creating
val implementation by configurations.getting

implementation.extendsFrom(shade)

val api by configurations.getting

api.extendsFrom(shade)

dependencies {
  compileOnly(libs.jspecify)

  // Chicory annotation processor (@WasmModuleInterface, @HostModule)
  compileOnly(libs.chicory.annotations)
  annotationProcessor(libs.chicory.annotations.processor)

  implementation(project(":sdk-common"))
  implementation(libs.log4j.api)
  implementation(libs.opentelemetry.api)

  // We need this for the manifest
  implementation(libs.jackson.annotations)
  implementation(libs.jackson.databind)

  // Chicory runtime + Jackson CBOR for the WASM bridge — shaded into the jar
  implementation(libs.chicory.runtime)
  implementation(libs.jackson.cbor)

  // We don't want a hard-dependency on it
  compileOnly(libs.log4j.core)

  testCompileOnly(libs.jspecify)
  testAnnotationProcessor(project(":sdk-api-gen"))
  kspTest(project(":sdk-api-kotlin-gen"))
  testImplementation(libs.log4j.api)
  testImplementation(project(":sdk-common"))
  testImplementation(project(":client"))
  testImplementation(project(":client-kotlin"))
  testImplementation(project(":sdk-api"))
  testImplementation(project(":sdk-api-kotlin"))
  testImplementation(project(":sdk-http-vertx"))
  testImplementation(project(":sdk-lambda"))
  testImplementation(libs.jackson.annotations)
  testImplementation(libs.jackson.databind)
  testImplementation(libs.jackson.cbor)
  testImplementation(libs.opentelemetry.api)
  testImplementation(libs.chicory.runtime)
  testImplementation(libs.mutiny)
  testImplementation(libs.junit.jupiter)
  testImplementation(libs.assertj)
  testImplementation(libs.log4j.core)
  testImplementation(libs.kotlinx.coroutines.core)
  testImplementation(libs.kotlinx.serialization.core)
  testImplementation(libs.vertx.junit5)
  testImplementation(libs.vertx.kotlin.coroutines)
  testRuntimeOnly(libs.junit.platform.launcher)
}

// ---------------------------------------------------------------------------
// Source sets
// ---------------------------------------------------------------------------

val generatedJ2SPDir = layout.buildDirectory.dir("generated/j2sp")

sourceSets {
  main {
    java.srcDir(generatedJ2SPDir)
    java.srcDir(generatedWasmMarkerDir)
    resources.srcDir(wasmResourceDir)
  }
}

// ---------------------------------------------------------------------------
// jsonSchema2Pojo
// ---------------------------------------------------------------------------

jsonSchema2Pojo {
  setSource(files("$projectDir/src/main/service-protocol/endpoint_manifest_schema.json"))
  targetPackage = "dev.restate.sdk.core.generated.manifest"
  targetDirectory = generatedJ2SPDir.get().asFile
  useLongIntegers = true
  includeSetters = true
  includeGetters = true
  generateBuilders = true
}

// ---------------------------------------------------------------------------
// Task wiring
// ---------------------------------------------------------------------------

tasks {
  withType<JavaCompile> {
    dependsOn(generateJsonSchema2Pojo, generateWasmMarker, "precompileWasm2Class")

    val disabledClassesCodegen =
        listOf(
            "dev.restate.sdk.core.javaapi.reflections.MyWorkflow",
            "dev.restate.sdk.core.javaapi.reflections.RawInputOutput",
            "dev.restate.sdk.core.javaapi.reflections.RawService",
        )

    options.compilerArgs.addAll(
        listOf(
            "-parameters",
            "-Adev.restate.codegen.disabledClasses=${disabledClassesCodegen.joinToString(",")}",
        )
    )
  }
  withType<KotlinCompile>().configureEach { dependsOn(generateJsonSchema2Pojo) }
  withType<org.gradle.jvm.tasks.Jar>().configureEach {
    dependsOn(generateJsonSchema2Pojo, generateWasmMarker)
  }
  withType<AbstractDokkaTask>().configureEach {
    dependsOn(generateJsonSchema2Pojo, generateWasmMarker)
  }
}

ksp {
  val disabledClassesCodegen =
      listOf(
          "dev.restate.sdk.core.kotlinapi.reflections.Empty",
          "dev.restate.sdk.core.kotlinapi.reflections.PrimitiveTypes",
          "dev.restate.sdk.core.kotlinapi.reflections.CornerCases",
          "dev.restate.sdk.core.kotlinapi.reflections.RawInputOutput",
          "dev.restate.sdk.core.kotlinapi.reflections.MyWorkflow",
          "dev.restate.sdk.core.kotlinapi.reflections.GreeterWithExplicitName",
      )
  arg("dev.restate.codegen.disabledClasses", disabledClassesCodegen.joinToString(","))
}
