// Copyright (c) 2023 - Restate Software, Inc., Restate GmbH
//
// This file is part of the Restate Java SDK,
// which is released under the MIT license.
//
// You can find a copy of the license in file LICENSE in the root
// directory of this repository or package, or at
// https://github.com/restatedev/sdk-java/blob/main/LICENSE
package dev.restate.integration;

/** Send result metadata. */
@org.jetbrains.annotations.ApiStatus.Experimental
public interface SendResult {

  /**
   * Returns the offset assigned to this invocation within the producer's sequence. For an {@link
   * ExactlyOnceProducer} this is the offset you supplied; otherwise it is autogenerated.
   *
   * @return the assigned offset
   */
  long offset();
}
