name: Bump version
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to bump (without prepending "v")'
        required: true

jobs:
  bump:
    name: Bump release version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install dasel
        run: curl -sSLf "https://github.com/tomwright/dasel/releases/download/v2.8.1/dasel_linux_amd64" -L -o dasel && chmod +x dasel && mv ./dasel /usr/local/bin/dasel
      - name: Bump version overwriting libs.versions.toml
        run: dasel put -f gradle/libs.versions.toml -t string -v "${{ github.event.inputs.version }}" 'versions.restate'
      - name: Create version bump PR
        uses: peter-evans/create-pull-request@v8
        with:
          title: "[Release] Bump to ${{ github.event.inputs.version }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Bump to ${{ github.event.inputs.version }}"
          signoff: true
          branch: "bump/${{ github.event.inputs.version }}"
          body: >
            This PR performs the bump of the SDK to ${{ github.event.inputs.version }}.
            This PR is auto-generated by
            [create-pull-request](https://github.com/peter-evans/create-pull-request).