name: Docker

on:    
  push:    
    branches: [main]    
    tags:    
      - v**

env:
  REPOSITORY_OWNER: ${{ github.repository_owner }}
  GHCR_REGISTRY: "ghcr.io"
  GHCR_REGISTRY_USERNAME: ${{ github.actor }}
  GHCR_REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  sdk-test-docker:
    if: github.repository_owner == 'restatedev'
    runs-on: warp-ubuntu-latest-x64-4x
    name: "Create test-services Docker Image (JRE ${{ matrix.jreVersion }})"
    strategy:
      fail-fast: false
      matrix:
        jreVersion: [ 17, 21, 25 ]

    steps:
      - uses: actions/checkout@v6
        with:
          repository: restatedev/sdk-java

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-workspaces: sdk-core/src/main/rust

      - name: Log into GitHub container registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ env.GHCR_REGISTRY_USERNAME }}
          password: ${{ env.GHCR_REGISTRY_TOKEN }}

      - name: Build restatedev/test-services-java image (JRE ${{ matrix.jreVersion }})
        run: ./gradlew -Djib.console=plain :test-services:jibDockerBuild -PtestServicesJre=${{ matrix.jreVersion }}

      - name: Push restatedev/test-services-java image
        run: |
          docker tag restatedev/test-services-java ghcr.io/restatedev/test-services-java:main-jre${{ matrix.jreVersion }}
          docker push ghcr.io/restatedev/test-services-java:main-jre${{ matrix.jreVersion }}
