name: Trigger release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v**


jobs:
  publish-to-github-packages:
    uses: ./.github/workflows/release.yml
    secrets: inherit
