name: Tests

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and test (Java ${{ matrix.java }})
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        java: [ 17, 21 ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Pull Restate docker image
        run: docker pull ghcr.io/restatedev/restate:main

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Test results (Java ${{ matrix.java }})
          path: "**/test-results/test/*.xml"

  test-javadocs:
    name: Test Javadocs and dokka
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          # We test with same Java version and distribution used by the Docs script
          # https://github.com/restatedev/documentation/blob/main/.github/workflows/pre-release.yml
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build Javadocs
        run: gradle :sdk-aggregated-javadocs:javadoc
      - name: Build Kotlin docs
        run: gradle :dokkaHtmlMultiModule

  event_file:
    name: "Event File"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Event File
          path: ${{ github.event_path }}
